package cn.pangpython.mybatisonly.model;

import java.util.Date;

public class Employe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.emp_no
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private Integer emp_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.birth_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private Date birth_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.first_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private String first_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private String last_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.gender
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    private Date hire_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.emp_no
     *
     * @return the value of employees.emp_no
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public Integer getEmp_no() {
        return emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.emp_no
     *
     * @param emp_no the value for employees.emp_no
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setEmp_no(Integer emp_no) {
        this.emp_no = emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.birth_date
     *
     * @return the value of employees.birth_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public Date getBirth_date() {
        return birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.birth_date
     *
     * @param birth_date the value for employees.birth_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setBirth_date(Date birth_date) {
        this.birth_date = birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.first_name
     *
     * @return the value of employees.first_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.first_name
     *
     * @param first_name the value for employees.first_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name == null ? null : first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.last_name
     *
     * @return the value of employees.last_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public String getLast_name() {
        return last_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.last_name
     *
     * @param last_name the value for employees.last_name
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setLast_name(String last_name) {
        this.last_name = last_name == null ? null : last_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.gender
     *
     * @return the value of employees.gender
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.gender
     *
     * @param gender the value for employees.gender
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hire_date
     *
     * @return the value of employees.hire_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public Date getHire_date() {
        return hire_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hire_date
     *
     * @param hire_date the value for employees.hire_date
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    public void setHire_date(Date hire_date) {
        this.hire_date = hire_date;
    }

    @Override
    public String toString() {
        return "Employe{" +
                "emp_no=" + emp_no +
                ", birth_date=" + birth_date +
                ", first_name='" + first_name + '\'' +
                ", last_name='" + last_name + '\'' +
                ", gender='" + gender + '\'' +
                ", hire_date=" + hire_date +
                '}';
    }
}