package cn.pangpython.mybatisonly.dao;

import cn.pangpython.mybatisonly.model.Employe;
import cn.pangpython.mybatisonly.model.EmployeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    long countByExample(EmployeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int deleteByExample(EmployeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int deleteByPrimaryKey(Integer emp_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int insert(Employe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int insertSelective(Employe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    List<Employe> selectByExample(EmployeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    Employe selectByPrimaryKey(Integer emp_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employe record, @Param("example") EmployeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int updateByExample(@Param("record") Employe record, @Param("example") EmployeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int updateByPrimaryKeySelective(Employe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Sun May 26 17:41:38 CST 2019
     */
    int updateByPrimaryKey(Employe record);
}